[package]
name = "fp-rust"
version = "0.1.0"
authors = ["alfinsuryaS <benjaminstwo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "main"
path = "module/main.rs"